### ISSUE TITLE
Add flagged frequency information to DB

### ISSUE THREAD

**Issue by talonmyburgh** [COSMIC-SETI/COSMIC-VLA-DelayEngine#17]
So as not to store 2 boolean lists per antenna - each 1024 long, come up with an encoding and store one integer per antenna that can be decoded to describe flagged channels.

**Comment by talonmyburgh** [comment]
Turns out - 1024bit integers don't exist for a reason. Not sure why we thought this might be a way to store a single value in the `db` @radonnachie :)

@Chenoachem is it important to know from the database which channels where flagged - i.e. a list of frequencies or ordered boolean values? Since we don't store the channel values in the database perhaps this is not necessary, and percentage flagged would be sufficient? Though that gives no information about which channels were flagged.

**Comment by Chenoachem** [comment]
For what we are doing here % is all we need. When we get to the point where we start to flag channels based on a database before the search, then the frequencies flagged will be important.

**Comment by talonmyburgh** [comment]
Okay, while we do have that information in saved files with the calibration solutions, the difficulty is ever adding it as a field to the database. So, to clarify, are you saying that the database need only ever contain %flagged frequencies?

**Comment by Chenoachem** [comment]
That is correct. % flagged for calibration only. :)

**Comment by talonmyburgh** [comment]
Done with a8f86c2b9e6a27c57cf5802ae482da684791a485
