### ISSUE TITLE
Store list of uncalibrated channels

### ISSUE THREAD

**Issue by talonmyburgh** [COSMIC-SETI/COSMIC-VLA-DelayEngine#18]
We want to have a list associated with every calibration run in the database that says which frequencies were not corrected for. This is likely to be quite a large product that we save to the database.

**Comment by Chenoachem** [comment]
Not sure it needs to be in the database. Maybe create a short-term list?  The idea is to not bother doing a search and stamp process if we don't have the block of channels calibrated.

**Comment by talonmyburgh** [comment]
Ah right yes - it needs to notify the recording process not to record those channels if possible. At the very least, don't beamform/search those channels :)

**Comment by talonmyburgh** [comment]
Completed. We store number of processed channels per tuning and number of flagged frequencies. From this one is able to deduce a % of flagged frequencies.
This product is saved to the `AntennaCalibration` database.
